[package]
name = "index"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tongrams =  { path = "../tongrams" }
anyhow = "1.0"
structopt = "0.3"  # MIT or Apache-2.0
