[package]
name = "tongrams"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sucds = "0.1.4"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
byteorder = "1.4.3"
